version: "3.6"
services:
  lb:
    container_name: "tw_lb"
    restart: always
    build:
      context: ./haproxy
    ports:
      - 80:80
  service_register:
    container_name: "tw_service_register"
    image: consul:latest
    ports:
      - "8500:8500" 
  redis:
    container_name: "tw_redis"
    image: redis:alpine
    ports: 
      - "6379:6379"
    volumes:
      - db:/var/lib/redis/data
  database:
    container_name: "tw_database"
    image: postgres:12.13-alpine
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=twitter
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data  
volumes:
  db:
